import { HomeAssistant } from './types';

type Dict = Record<string, string>;

const en: Dict = {
  // common fields
  entry_id: 'Prometheus server',
  query: 'PromQL query',
  name: 'Name',
  title: 'Title',
  icon: 'Icon',
  unit: 'Unit',
  decimals: 'Decimals',
  refresh_interval: 'Refresh interval (s)',
  min: 'Min',
  max: 'Max',
  arc_width: 'Arc width',
  sparkline: 'Show sparkline',
  sparkline_hours: 'Sparkline range (hours)',
  time_range: 'Time range',
  step: 'Step (s, empty = auto)',
  fill: 'Fill area',
  show_legend: 'Show legend',
  height: 'Chart height (px)',
  orientation: 'Orientation',
  show_values: 'Show values',
  bar_height: 'Bar height (px)',
  value: 'Value',
  color: 'Color',
  // sections
  section_display: 'Display',
  section_advanced: 'Advanced',
  section_thresholds: 'Thresholds',
  section_series: 'Series',
  // helpers
  helper_entry_id: 'Leave empty to use the first configured server',
  helper_unit: 'Values are scaled within the dimension (B → KiB → MiB, W → kW, s → min → h). You can also type a custom suffix',
  helper_thresholds: 'The color of the highest threshold not greater than the value is used',
  // actions
  add_threshold: 'Add threshold',
  add_series: 'Add series',
  remove: 'Remove',
  series_n: 'Series {n}',
  // options
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  // card states
  no_query: 'Set a PromQL query in the card editor',
  no_series: 'Add at least one series in the card editor',
  no_data: 'No data',
  // card picker
  stat_name: 'Prometheus Stat',
  stat_desc: 'Single Prometheus metric value with optional sparkline',
  gauge_name: 'Prometheus Gauge',
  gauge_desc: 'Radial gauge with threshold colors',
  timeseries_name: 'Prometheus Time Series',
  timeseries_desc: 'Grafana-like line/area chart for one or more PromQL queries',
  bar_name: 'Prometheus Bar Chart',
  bar_desc: 'Bar chart grouped by a Prometheus label',
  // v0.3
  legend_format: 'Legend format',
  helper_legend_format: 'Grafana syntax: {{instance}} {{job}}. Empty = metric{labels}',
  helper_name_series: 'Series name or legend format, e.g. {{device}} rx',
  palette: 'Color scheme',
  palette_classic: 'Classic palette (Grafana)',
  'palette_green-yellow-red': 'Green-Yellow-Red (by series)',
  palette_blues: 'Blues (by series)',
  palette_greens: 'Greens (by series)',
  palette_reds: 'Reds (by series)',
  palette_purples: 'Purples (by series)',
  palette_single: 'Single color (theme)',
  color_mode: 'Color by',
  color_mode_thresholds: 'Thresholds',
  color_mode_series: 'Series palette',
  line_width: 'Line width',
  fill_opacity: 'Fill opacity (%)',
  sparkline_fill: 'Sparkline gradient',
  reduce: 'Several series',
  reduce_none: 'Show each series',
  reduce_sum: 'Sum',
  reduce_avg: 'Average',
  reduce_min: 'Min',
  reduce_max: 'Max',
  show_labels: 'Show series labels',
  stacked: 'Stack series',
  legend_mode: 'Legend mode',
  legend_mode_list: 'List',
  legend_mode_table: 'Table',
  legend_values: 'Legend values',
  legend_value_last: 'Last',
  legend_value_min: 'Min',
  legend_value_max: 'Max',
  legend_value_mean: 'Mean',
  sort: 'Sort',
  sort_desc: 'Value, descending',
  sort_asc: 'Value, ascending',
  sort_name: 'Name',
  sort_none: 'As returned',
  limit: 'Max bars',
  section_legend: 'Legend',
  section_colors: 'Colors',
  section_queries: 'Queries',
  add_query: 'Add query',
  query_n: 'Query {n}',
  helper_series_query: 'A query may return many series; each gets its own color and legend entry',
  // v0.4
  transparent: 'Transparent background',
  show_current: 'Show current / hovered value',
  current: 'Current',
  layout: 'Layout',
  layout_default: 'Value with icon',
  layout_tiles: 'Colored tiles (Grafana)',
  tile_style: 'Tile background',
  tile_style_gradient: 'Gradient',
  tile_style_solid: 'Solid',
  tile_height: 'Tile height',
  tile_min_width: 'Tile min width',
  timeline_name: 'Prometheus State Timeline',
  timeline_desc: 'Grafana-like state timeline: value changes over time as colored bands',
  pie_name: 'Prometheus Pie Chart',
  pie_desc: 'Pie / donut chart, one slice per returned series',
  row_height: 'Row height',
  merge_values: 'Merge equal values',
  section_mappings: 'Value mappings',
  helper_mappings: 'Exact value (e.g. 1) or range from..to → text and color. Unmapped values use thresholds or the palette',
  add_mapping: 'Add mapping',
  from: 'From',
  to: 'To',
  text: 'Text',
  helper_timeline_query: 'Each returned series is a row. Name: plain text or {{label}}',
  helper_pie_query: 'Instant query; each returned series is a slice. Name: plain text or {{label}}',
  pie_type: 'Type',
  pie_type_donut: 'Donut',
  pie_type_pie: 'Pie',
  donut_width: 'Donut width',
  show_total: 'Total in the center',
  size: 'Size',
  legend_position: 'Legend position',
  legend_position_right: 'Right',
  legend_position_bottom: 'Bottom',
  legend_pie_value: 'Value',
  legend_pie_percent: 'Percent',
  other: 'Other',
  total: 'Total',
  // v0.5
  test_query: 'Test query',
  testing: 'Testing…',
  test_ok: '✓ {n} series ({type}), {ms} ms',
  autocomplete_hint: 'Ctrl+Space — suggestions',
  bargauge_name: 'Prometheus Bar Gauge',
  bargauge_desc: 'Grafana-like bar gauges with threshold colors, one per series',
  table_name: 'Prometheus Table',
  table_desc: 'Instant query as a table: labels as columns, sortable',
  heatmap_name: 'Prometheus Heatmap',
  heatmap_desc: 'Heatmap of histogram buckets or many series over time',
  alerts_name: 'Prometheus Alerts',
  alerts_desc: 'List of active Prometheus alerts',
  grid_name: 'Prometheus Grid',
  grid_desc: 'Layout grid: rows with any number of cards and width ratios (e.g. 25/25/50) on a shared background',
  display_mode: 'Display mode',
  display_mode_gradient: 'Gradient',
  display_mode_basic: 'Basic',
  display_mode_lcd: 'LCD (segments)',
  show_unfilled: 'Show unfilled area',
  columns: 'Columns (labels)',
  helper_columns: 'Label names to show; empty = all labels',
  hide_columns: 'Hidden labels',
  value_column: 'Value column title',
  sort_by: 'Sort by',
  sort_by_value: 'Value',
  sort_by_label: 'First label',
  sort_dir: 'Direction',
  sort_dir_desc: 'Descending',
  sort_dir_asc: 'Ascending',
  max_rows: 'Max rows',
  color_cells: 'Color value cells by thresholds',
  heatmap_mode: 'Data',
  heatmap_mode_histogram: 'Histogram buckets (le label)',
  heatmap_mode_series: 'Series as rows',
  color_scheme: 'Color scheme',
  scheme_oranges: 'Oranges',
  scheme_spectral: 'Spectral',
  scheme_viridis: 'Viridis',
  scheme_blues: 'Blues',
  scheme_greens: 'Greens',
  scheme_reds: 'Reds',
  scheme_purples: 'Purples',
  log_scale: 'Logarithmic colors',
  show_legend_scale: 'Show color scale',
  state_filter: 'States',
  state_firing: 'Firing',
  state_pending: 'Pending',
  state_inactive: 'Inactive',
  severity_filter: 'Severity (comma separated, empty = all)',
  show_labels_alerts: 'Show labels',
  show_annotations: 'Show summary / description',
  no_alerts: 'No active alerts',
  active_since: 'since {time}',
  rows: 'Rows',
  row_n: 'Row {n}',
  add_row: 'Add row',
  add_card: 'Add card',
  widths: 'Widths (%)',
  helper_widths: 'Comma separated, e.g. 25,25,50. Empty = equal widths',
  gap: 'Gap',
  row_height_grid: 'Row height (px, empty = auto)',
  background: 'Background',
  background_card: 'Card',
  background_transparent: 'Transparent',
  background_custom: 'Custom color',
  background_color: 'Background color',
  inner_transparent: 'Transparent inner cards',
  stack_on_mobile: 'One card per row on narrow screens',
  edit_card: 'Edit',
  move_up: 'Move up',
  move_down: 'Move down',
  card_n: 'Card {n}',
  empty_row: 'Empty row — add a card in the editor',
  unit_col: 'Unit',
  states: 'States',
  severities: 'Severity (comma separated, empty = all)',
  name_filter: 'Alert name filter (text or regex)'
};

const ru: Dict = {
  entry_id: 'Сервер Prometheus',
  query: 'Запрос PromQL',
  name: 'Название',
  title: 'Заголовок',
  icon: 'Иконка',
  unit: 'Единица измерения',
  decimals: 'Знаков после запятой',
  refresh_interval: 'Интервал обновления (с)',
  min: 'Минимум',
  max: 'Максимум',
  arc_width: 'Толщина дуги',
  sparkline: 'Показывать мини-график',
  sparkline_hours: 'Период мини-графика (ч)',
  time_range: 'Период',
  step: 'Шаг (с, пусто = авто)',
  fill: 'Заливка области',
  show_legend: 'Показывать легенду',
  height: 'Высота графика (px)',
  orientation: 'Ориентация',
  show_values: 'Показывать значения',
  bar_height: 'Высота столбца (px)',
  value: 'Значение',
  color: 'Цвет',
  section_display: 'Отображение',
  section_advanced: 'Дополнительно',
  section_thresholds: 'Пороги',
  section_series: 'Серии',
  helper_entry_id: 'Оставьте пустым, чтобы использовать первый настроенный сервер',
  helper_unit: 'Значение масштабируется в пределах размерности (B → KiB → MiB, W → kW, s → мин → ч). Можно ввести свой суффикс',
  helper_thresholds: 'Используется цвет наибольшего порога, не превышающего значение',
  add_threshold: 'Добавить порог',
  add_series: 'Добавить серию',
  remove: 'Удалить',
  series_n: 'Серия {n}',
  horizontal: 'Горизонтально',
  vertical: 'Вертикально',
  no_query: 'Укажите запрос PromQL в редакторе карточки',
  no_series: 'Добавьте хотя бы одну серию в редакторе карточки',
  no_data: 'Нет данных',
  stat_name: 'Prometheus: значение',
  stat_desc: 'Одно значение метрики Prometheus с мини-графиком',
  gauge_name: 'Prometheus: индикатор',
  gauge_desc: 'Круговой индикатор с цветовыми порогами',
  timeseries_name: 'Prometheus: временной ряд',
  timeseries_desc: 'График в стиле Grafana для одного или нескольких запросов PromQL',
  bar_name: 'Prometheus: столбцы',
  bar_desc: 'Столбчатая диаграмма с группировкой по метке Prometheus',
  legend_format: 'Формат легенды',
  helper_legend_format: 'Синтаксис Grafana: {{instance}} {{job}}. Пусто = metric{labels}',
  helper_name_series: 'Имя серии или формат легенды, например {{device}} rx',
  palette: 'Цветовая схема',
  palette_classic: 'Классическая палитра (Grafana)',
  'palette_green-yellow-red': 'Зелёный-жёлтый-красный (по сериям)',
  palette_blues: 'Синие (по сериям)',
  palette_greens: 'Зелёные (по сериям)',
  palette_reds: 'Красные (по сериям)',
  palette_purples: 'Фиолетовые (по сериям)',
  palette_single: 'Один цвет (тема)',
  color_mode: 'Цвет по',
  color_mode_thresholds: 'Порогам',
  color_mode_series: 'Палитре серий',
  line_width: 'Толщина линии',
  fill_opacity: 'Прозрачность заливки (%)',
  sparkline_fill: 'Градиент под мини-графиком',
  reduce: 'Несколько серий',
  reduce_none: 'Показать каждую',
  reduce_sum: 'Сумма',
  reduce_avg: 'Среднее',
  reduce_min: 'Минимум',
  reduce_max: 'Максимум',
  show_labels: 'Подписи серий',
  stacked: 'Накопление (stack)',
  legend_mode: 'Вид легенды',
  legend_mode_list: 'Список',
  legend_mode_table: 'Таблица',
  legend_values: 'Значения в легенде',
  legend_value_last: 'Последнее',
  legend_value_min: 'Мин',
  legend_value_max: 'Макс',
  legend_value_mean: 'Среднее',
  sort: 'Сортировка',
  sort_desc: 'По значению, убыв.',
  sort_asc: 'По значению, возр.',
  sort_name: 'По имени',
  sort_none: 'Как вернул Prometheus',
  limit: 'Максимум столбцов',
  section_legend: 'Легенда',
  section_colors: 'Цвета',
  section_queries: 'Запросы',
  add_query: 'Добавить запрос',
  query_n: 'Запрос {n}',
  helper_series_query: 'Запрос может вернуть много серий — у каждой свой цвет и строка в легенде',
  transparent: 'Прозрачный фон',
  show_current: 'Показывать текущее / выделенное значение',
  current: 'Текущее',
  layout: 'Вид',
  layout_default: 'Значение с иконкой',
  layout_tiles: 'Цветные плашки (Grafana)',
  tile_style: 'Фон плашки',
  tile_style_gradient: 'Градиент',
  tile_style_solid: 'Сплошной',
  tile_height: 'Высота плашки',
  tile_min_width: 'Мин. ширина плашки',
  timeline_name: 'Prometheus: шкала состояний',
  timeline_desc: 'Шкала состояний как в Grafana: изменения значения во времени цветными полосами',
  pie_name: 'Prometheus: круговая диаграмма',
  pie_desc: 'Круговая / кольцевая диаграмма, сектор на каждую серию',
  row_height: 'Высота строки',
  merge_values: 'Объединять одинаковые значения',
  section_mappings: 'Сопоставление значений',
  helper_mappings: 'Точное значение (например 1) или диапазон от..до → текст и цвет. Остальные значения — по порогам или палитре',
  add_mapping: 'Добавить сопоставление',
  from: 'От',
  to: 'До',
  text: 'Текст',
  helper_timeline_query: 'Каждая серия — отдельная строка. Название: текст или {{label}}',
  helper_pie_query: 'Мгновенный запрос; каждая серия — сектор. Название: текст или {{label}}',
  pie_type: 'Тип',
  pie_type_donut: 'Кольцо',
  pie_type_pie: 'Круг',
  donut_width: 'Толщина кольца',
  show_total: 'Сумма в центре',
  size: 'Размер',
  legend_position: 'Положение легенды',
  legend_position_right: 'Справа',
  legend_position_bottom: 'Снизу',
  legend_pie_value: 'Значение',
  legend_pie_percent: 'Процент',
  other: 'Прочее',
  total: 'Всего',
  test_query: 'Проверить запрос',
  testing: 'Проверка…',
  test_ok: '✓ Серий: {n} ({type}), {ms} мс',
  autocomplete_hint: 'Ctrl+Пробел — подсказки',
  bargauge_name: 'Prometheus: шкалы',
  bargauge_desc: 'Горизонтальные шкалы как в Grafana, цвет по порогам, по одной на серию',
  table_name: 'Prometheus: таблица',
  table_desc: 'Мгновенный запрос в виде таблицы: метки — столбцы, сортировка',
  heatmap_name: 'Prometheus: тепловая карта',
  heatmap_desc: 'Тепловая карта бакетов гистограммы или множества серий во времени',
  alerts_name: 'Prometheus: алерты',
  alerts_desc: 'Список активных алертов Prometheus',
  grid_name: 'Prometheus: сетка',
  grid_desc: 'Сетка для компоновки: строки с любым числом карточек и долями ширины (например 25/25/50) на общем фоне',
  display_mode: 'Режим отображения',
  display_mode_gradient: 'Градиент',
  display_mode_basic: 'Простой',
  display_mode_lcd: 'LCD (сегменты)',
  show_unfilled: 'Показывать незаполненную часть',
  columns: 'Столбцы (метки)',
  helper_columns: 'Имена меток для показа; пусто = все метки',
  hide_columns: 'Скрытые метки',
  value_column: 'Заголовок столбца значения',
  sort_by: 'Сортировать по',
  sort_by_value: 'Значению',
  sort_by_label: 'Первой метке',
  sort_dir: 'Направление',
  sort_dir_desc: 'По убыванию',
  sort_dir_asc: 'По возрастанию',
  max_rows: 'Максимум строк',
  color_cells: 'Цвет ячеек значения по порогам',
  heatmap_mode: 'Данные',
  heatmap_mode_histogram: 'Бакеты гистограммы (метка le)',
  heatmap_mode_series: 'Серии как строки',
  color_scheme: 'Цветовая схема',
  scheme_oranges: 'Оранжевая',
  scheme_spectral: 'Спектральная',
  scheme_viridis: 'Viridis',
  scheme_blues: 'Синяя',
  scheme_greens: 'Зелёная',
  scheme_reds: 'Красная',
  scheme_purples: 'Фиолетовая',
  log_scale: 'Логарифмическая шкала цвета',
  show_legend_scale: 'Показывать шкалу цвета',
  state_filter: 'Состояния',
  state_firing: 'Активные (firing)',
  state_pending: 'Ожидающие (pending)',
  state_inactive: 'Неактивные',
  severity_filter: 'Severity (через запятую, пусто = все)',
  show_labels_alerts: 'Показывать метки',
  show_annotations: 'Показывать summary / description',
  no_alerts: 'Активных алертов нет',
  active_since: 'с {time}',
  rows: 'Строки',
  row_n: 'Строка {n}',
  add_row: 'Добавить строку',
  add_card: 'Добавить карточку',
  widths: 'Ширины (%)',
  helper_widths: 'Через запятую, например 25,25,50. Пусто = поровну',
  gap: 'Отступ',
  row_height_grid: 'Высота строки (px, пусто = авто)',
  background: 'Фон',
  background_card: 'Карточка',
  background_transparent: 'Прозрачный',
  background_custom: 'Свой цвет',
  background_color: 'Цвет фона',
  inner_transparent: 'Прозрачные вложенные карточки',
  stack_on_mobile: 'На узком экране — по одной карточке в строке',
  edit_card: 'Изменить',
  move_up: 'Выше',
  move_down: 'Ниже',
  card_n: 'Карточка {n}',
  empty_row: 'Пустая строка — добавьте карточку в редакторе',
  unit_col: 'Ед.',
  states: 'Состояния',
  severities: 'Severity (через запятую, пусто = все)',
  name_filter: 'Фильтр по имени алерта (текст или regex)'
};

const DICTS: Record<string, Dict> = { en, ru };

function currentLanguage(hass?: HomeAssistant): string {
  const lang =
    hass?.locale?.language ||
    hass?.language ||
    (typeof localStorage !== 'undefined' ? localStorage.getItem('selectedLanguage')?.replace(/"/g, '') : null) ||
    (typeof navigator !== 'undefined' ? navigator.language : 'en') ||
    'en';
  return lang.split('-')[0].toLowerCase();
}

export function localize(key: string, hass?: HomeAssistant, vars: Record<string, string | number> = {}): string {
  const dict = DICTS[currentLanguage(hass)] || en;
  let text = dict[key] ?? en[key] ?? key;
  for (const [k, v] of Object.entries(vars)) {
    text = text.replace(`{${k}}`, String(v));
  }
  return text;
}
