import { HomeAssistant } from './types';

type Dict = Record<string, string>;

const en: Dict = {
  // common fields
  entry_id: 'Prometheus server',
  query: 'PromQL query',
  name: 'Name',
  title: 'Title',
  icon: 'Icon',
  unit: 'Unit',
  decimals: 'Decimals',
  refresh_interval: 'Refresh interval (s)',
  min: 'Min',
  max: 'Max',
  arc_width: 'Arc width',
  sparkline: 'Show sparkline',
  sparkline_hours: 'Sparkline range (hours)',
  time_range: 'Time range',
  step: 'Step (s, empty = auto)',
  fill: 'Fill area',
  show_legend: 'Show legend',
  height: 'Chart height (px)',
  group_by: 'Group by label',
  orientation: 'Orientation',
  show_values: 'Show values',
  bar_height: 'Bar height (px)',
  value: 'Value',
  color: 'Color',
  // sections
  section_display: 'Display',
  section_advanced: 'Advanced',
  section_thresholds: 'Thresholds',
  section_series: 'Series',
  // helpers
  helper_entry_id: 'Leave empty to use the first configured server',
  helper_unit: 'Values are scaled within the dimension (B → KiB → MiB, W → kW, s → min → h). You can also type a custom suffix',
  helper_group_by: 'Label whose value is used as the bar name (e.g. job, instance)',
  helper_thresholds: 'The color of the highest threshold not greater than the value is used',
  // actions
  add_threshold: 'Add threshold',
  add_series: 'Add series',
  remove: 'Remove',
  series_n: 'Series {n}',
  // options
  horizontal: 'Horizontal',
  vertical: 'Vertical',
  // card states
  no_query: 'Set a PromQL query in the card editor',
  no_series: 'Add at least one series in the card editor',
  no_data: 'No data',
  // card picker
  stat_name: 'Prometheus Stat',
  stat_desc: 'Single Prometheus metric value with optional sparkline',
  gauge_name: 'Prometheus Gauge',
  gauge_desc: 'Radial gauge with threshold colors',
  timeseries_name: 'Prometheus Time Series',
  timeseries_desc: 'Grafana-like line/area chart for one or more PromQL queries',
  bar_name: 'Prometheus Bar Chart',
  bar_desc: 'Bar chart grouped by a Prometheus label',
  // v0.3
  legend_format: 'Legend format',
  helper_legend_format: 'Grafana syntax: {{instance}} {{job}}. Empty = metric{labels}',
  helper_name_series: 'Series name or legend format, e.g. {{device}} rx',
  palette: 'Color scheme',
  palette_classic: 'Classic palette (Grafana)',
  'palette_green-yellow-red': 'Green-Yellow-Red (by series)',
  palette_blues: 'Blues (by series)',
  palette_greens: 'Greens (by series)',
  palette_reds: 'Reds (by series)',
  palette_purples: 'Purples (by series)',
  palette_single: 'Single color (theme)',
  color_mode: 'Color by',
  color_mode_thresholds: 'Thresholds',
  color_mode_series: 'Series palette',
  line_width: 'Line width',
  fill_opacity: 'Fill opacity (%)',
  sparkline_fill: 'Sparkline gradient',
  reduce: 'Several series',
  reduce_none: 'Show each series',
  reduce_sum: 'Sum',
  reduce_avg: 'Average',
  reduce_min: 'Min',
  reduce_max: 'Max',
  show_labels: 'Show series labels',
  stacked: 'Stack series',
  legend_mode: 'Legend mode',
  legend_mode_list: 'List',
  legend_mode_table: 'Table',
  legend_values: 'Legend values',
  legend_value_last: 'Last',
  legend_value_min: 'Min',
  legend_value_max: 'Max',
  legend_value_mean: 'Mean',
  sort: 'Sort',
  sort_desc: 'Value, descending',
  sort_asc: 'Value, ascending',
  sort_name: 'Name',
  sort_none: 'As returned',
  limit: 'Max bars',
  section_legend: 'Legend',
  section_colors: 'Colors',
  section_queries: 'Queries',
  add_query: 'Add query',
  query_n: 'Query {n}',
  helper_series_query: 'A query may return many series; each gets its own color and legend entry'
};

const ru: Dict = {
  entry_id: 'Сервер Prometheus',
  query: 'Запрос PromQL',
  name: 'Название',
  title: 'Заголовок',
  icon: 'Иконка',
  unit: 'Единица измерения',
  decimals: 'Знаков после запятой',
  refresh_interval: 'Интервал обновления (с)',
  min: 'Минимум',
  max: 'Максимум',
  arc_width: 'Толщина дуги',
  sparkline: 'Показывать мини-график',
  sparkline_hours: 'Период мини-графика (ч)',
  time_range: 'Период',
  step: 'Шаг (с, пусто = авто)',
  fill: 'Заливка области',
  show_legend: 'Показывать легенду',
  height: 'Высота графика (px)',
  group_by: 'Группировать по метке',
  orientation: 'Ориентация',
  show_values: 'Показывать значения',
  bar_height: 'Высота столбца (px)',
  value: 'Значение',
  color: 'Цвет',
  section_display: 'Отображение',
  section_advanced: 'Дополнительно',
  section_thresholds: 'Пороги',
  section_series: 'Серии',
  helper_entry_id: 'Оставьте пустым, чтобы использовать первый настроенный сервер',
  helper_unit: 'Значение масштабируется в пределах размерности (B → KiB → MiB, W → kW, s → мин → ч). Можно ввести свой суффикс',
  helper_group_by: 'Метка, значение которой станет подписью столбца (например job, instance)',
  helper_thresholds: 'Используется цвет наибольшего порога, не превышающего значение',
  add_threshold: 'Добавить порог',
  add_series: 'Добавить серию',
  remove: 'Удалить',
  series_n: 'Серия {n}',
  horizontal: 'Горизонтально',
  vertical: 'Вертикально',
  no_query: 'Укажите запрос PromQL в редакторе карточки',
  no_series: 'Добавьте хотя бы одну серию в редакторе карточки',
  no_data: 'Нет данных',
  stat_name: 'Prometheus: значение',
  stat_desc: 'Одно значение метрики Prometheus с мини-графиком',
  gauge_name: 'Prometheus: индикатор',
  gauge_desc: 'Круговой индикатор с цветовыми порогами',
  timeseries_name: 'Prometheus: временной ряд',
  timeseries_desc: 'График в стиле Grafana для одного или нескольких запросов PromQL',
  bar_name: 'Prometheus: столбцы',
  bar_desc: 'Столбчатая диаграмма с группировкой по метке Prometheus',
  legend_format: 'Формат легенды',
  helper_legend_format: 'Синтаксис Grafana: {{instance}} {{job}}. Пусто = metric{labels}',
  helper_name_series: 'Имя серии или формат легенды, например {{device}} rx',
  palette: 'Цветовая схема',
  palette_classic: 'Классическая палитра (Grafana)',
  'palette_green-yellow-red': 'Зелёный-жёлтый-красный (по сериям)',
  palette_blues: 'Синие (по сериям)',
  palette_greens: 'Зелёные (по сериям)',
  palette_reds: 'Красные (по сериям)',
  palette_purples: 'Фиолетовые (по сериям)',
  palette_single: 'Один цвет (тема)',
  color_mode: 'Цвет по',
  color_mode_thresholds: 'Порогам',
  color_mode_series: 'Палитре серий',
  line_width: 'Толщина линии',
  fill_opacity: 'Прозрачность заливки (%)',
  sparkline_fill: 'Градиент под мини-графиком',
  reduce: 'Несколько серий',
  reduce_none: 'Показать каждую',
  reduce_sum: 'Сумма',
  reduce_avg: 'Среднее',
  reduce_min: 'Минимум',
  reduce_max: 'Максимум',
  show_labels: 'Подписи серий',
  stacked: 'Накопление (stack)',
  legend_mode: 'Вид легенды',
  legend_mode_list: 'Список',
  legend_mode_table: 'Таблица',
  legend_values: 'Значения в легенде',
  legend_value_last: 'Последнее',
  legend_value_min: 'Мин',
  legend_value_max: 'Макс',
  legend_value_mean: 'Среднее',
  sort: 'Сортировка',
  sort_desc: 'По значению, убыв.',
  sort_asc: 'По значению, возр.',
  sort_name: 'По имени',
  sort_none: 'Как вернул Prometheus',
  limit: 'Максимум столбцов',
  section_legend: 'Легенда',
  section_colors: 'Цвета',
  section_queries: 'Запросы',
  add_query: 'Добавить запрос',
  query_n: 'Запрос {n}',
  helper_series_query: 'Запрос может вернуть много серий — у каждой свой цвет и строка в легенде'
};

const DICTS: Record<string, Dict> = { en, ru };

function currentLanguage(hass?: HomeAssistant): string {
  const lang =
    hass?.locale?.language ||
    hass?.language ||
    (typeof localStorage !== 'undefined' ? localStorage.getItem('selectedLanguage')?.replace(/"/g, '') : null) ||
    (typeof navigator !== 'undefined' ? navigator.language : 'en') ||
    'en';
  return lang.split('-')[0].toLowerCase();
}

export function localize(key: string, hass?: HomeAssistant, vars: Record<string, string | number> = {}): string {
  const dict = DICTS[currentLanguage(hass)] || en;
  let text = dict[key] ?? en[key] ?? key;
  for (const [k, v] of Object.entries(vars)) {
    text = text.replace(`{${k}}`, String(v));
  }
  return text;
}
